// data.jsx — complete KPI seed data for DSU ORIC PMS
// All 31 indicators: A1-A6, B1-B11, C1-C8, D1-D6
// Sections aligned to CLAUDE.md: A(10), B(45), C(30), D(15) = 100

const SECTIONS = [
  { id:'A', name:'Human Resource & Operations',       max:10, accent:'#6B1A1A' },
  { id:'B', name:'Research Excellence',               max:45, accent:'#1565C0' },
  { id:'C', name:'Innovation & Commercialization',    max:30, accent:'#2E7D32' },
  { id:'D', name:'Sustainability & Capacity Building',max:15, accent:'#E65100' },
];

const doc = (name, size, kind='pdf') => ({ name, size, kind });

const INDICATORS = [
  // ════════════════ SECTION A — Human Resource & Operations (max 10) ════════════════
  { code:'A1', section:'A', name:'ORIC Staffing Compliance', max:2, score:2, value:5, unit:'staff',
    desc:'Number of full-time ORIC staff against HEC-mandated minimum (≥5 staff required).',
    guide:'Score 2 if ≥5 staff · Score 1 if 3–4 · Score 0 if <3',
    reqDocs:['Staff appointment letters','ORIC org chart'],
    docs:[doc('ORIC_Org_Chart_2024.pdf','420 KB'), doc('Appointment_Letters.pdf','1.2 MB')],
    remarks:'ORIC fully staffed with 5 full-time members including Director.',
    status:'APPROVED',
    review:{ rating:'perfect', comment:'Staffing fully compliant and well documented.', reviewer:'HEC Reviewer', date:'2 days ago' } },

  { code:'A2', section:'A', name:'Annual ORIC Operating Budget', max:2, score:2, value:4.2, unit:'M PKR',
    desc:'Approved annual operating budget allocated to ORIC (in millions PKR).',
    guide:'Score 2 if ≥5M · Score 1 if 3–5M · Score 0 if <3M',
    reqDocs:['Budget approval document','Syndicate meeting minutes'],
    docs:[doc('Budget_Approval_FY25.pdf','680 KB')],
    remarks:'Budget of PKR 4.2M approved by Syndicate for FY2024-25.',
    status:'RETURNED',
    review:{ rating:'minor', comment:'Please attach the Syndicate meeting minutes that approved this budget.', reviewer:'HEC Reviewer', date:'1 day ago' } },

  { code:'A3', section:'A', name:'Research Policies & SOPs', max:2, score:2, value:6, unit:'policies',
    desc:'Number of approved research governance policies and SOPs in force.',
    guide:'Score 2 if ≥5 policies · Score 1 if 1–4 · Score 0 if none',
    reqDocs:['Policy documents','Approval notifications'],
    docs:[doc('Research_Policy_Manual.pdf','2.4 MB')],
    remarks:'6 policies including IP, ethics, and research misconduct SOPs.',
    status:'SUBMITTED', review:null },

  { code:'A4', section:'A', name:'Capacity-Building Trainings', max:2, score:0, value:0, unit:'sessions',
    desc:'Research capacity-building workshops and seminars conducted during the year.',
    guide:'Score 2 if ≥4 sessions · Score 1 if 1–3 · Score 0 if none',
    reqDocs:['Training attendance sheets','Event reports'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  { code:'A5', section:'A', name:'Faculty Research Incentive Policy', max:1, score:0, value:0, unit:'policies',
    desc:'Existence of a university-approved policy to incentivize faculty research output.',
    guide:'Score 1 if approved incentive policy documented and operational · Score 0 if none',
    reqDocs:['Approved incentive policy document'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  { code:'A6', section:'A', name:'ORIC Annual Report Published', max:1, score:0, value:0, unit:'reports',
    desc:'Annual ORIC performance report published and disseminated for the previous year.',
    guide:'Score 1 if annual report published and publicly available · Score 0 if not published',
    reqDocs:['Published annual report or proof of dissemination'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  // ════════════════ SECTION B — Research Excellence (max 45) ════════════════
  { code:'B1', section:'B', name:'HEC Research Proposals Submitted', max:4, score:4, value:8, unit:'proposals',
    denom:12, denomLabel:'PhD faculty members',
    desc:'Research proposals submitted to HEC, divided by number of PhD faculty.',
    guide:'Score 4 if ratio ≥1.0 · Score 3 if ≥0.5 · Score 1 if any submitted',
    reqDocs:['HEC submission confirmations','IRB / ethics approval (if any)'],
    docs:[doc('HEC_Submission_Receipts.pdf','940 KB'), doc('Ethics_Approval_B1.pdf','310 KB')],
    remarks:'8 proposals submitted across NRPU and TDF calls in Q1–Q2.',
    status:'SUBMITTED', review:null },

  { code:'B2', section:'B', name:'Research Grants Secured', max:6, score:5, value:3, unit:'grants',
    desc:'Number of competitive research grants awarded during the year.',
    guide:'Score 6 if ≥4 grants · Score 4 if 2–3 · Score 2 if 1',
    reqDocs:['Grant award letters','Disbursement evidence'],
    docs:[doc('NRPU_Award_Letter.pdf','520 KB'), doc('TDF_Grant_Sanction.pdf','480 KB')],
    remarks:'3 grants secured totalling PKR 41M (2 NRPU, 1 TDF).',
    status:'UNDER_REVIEW', review:null },

  { code:'B3', section:'B', name:'Impact-Factor Publications', max:9, score:9, value:34, unit:'papers',
    denom:48, denomLabel:'total faculty',
    desc:'Journal publications with JCR impact factor, normalised by faculty count.',
    guide:'Score 9 if ratio ≥1.0 · Score 6 if ≥0.6 · Score 3 if ≥0.3',
    reqDocs:['Publication list with DOIs','First-page PDFs'],
    docs:[doc('Publications_Master_List.xlsx','210 KB','xls'), doc('Paper_FirstPages.pdf','5.1 MB')],
    remarks:'34 Q1/Q2 publications; full list with DOIs attached.',
    status:'APPROVED',
    review:{ rating:'perfect', comment:'Strong publication output, well evidenced with DOIs. Approved.', reviewer:'HEC Reviewer', date:'3 days ago' } },

  { code:'B4', section:'B', name:'PhD Graduates Produced', max:6, score:4, value:6, unit:'graduates',
    desc:'PhD scholars who completed their degree during the assessment year.',
    guide:'Score 6 if ≥10 · Score 4 if 4–9 · Score 2 if 1–3',
    reqDocs:['Degree completion notifications','Thesis approval letters'],
    docs:[doc('PhD_Completion_2024.pdf','760 KB')],
    remarks:'6 PhD graduates across CS and EE departments.',
    status:'REJECTED',
    review:{ rating:'bad', comment:'Evidence attached lists enrolled scholars, not graduates. Provide degree-completion notifications signed by the Controller of Examinations.', reviewer:'HEC Reviewer', date:'1 day ago' } },

  { code:'B5', section:'B', name:'Citations Index (3-year)', max:4, score:0, value:0, unit:'citations',
    desc:'Total Scopus citations to faculty work over the last three years.',
    guide:'Score 4 if ≥2000 · Score 3 if ≥1000 · Score 1 if ≥400',
    reqDocs:['Scopus citation report (PDF screenshot)'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  { code:'B6', section:'B', name:'Post-doctoral Fellows', max:3, score:0, value:0, unit:'postdocs',
    desc:'Active post-doctoral researchers working at the university.',
    guide:'Score 3 if ≥5 postdocs · Score 2 if 2–4 · Score 1 if 1',
    reqDocs:['Postdoc appointment letters','Research plan approvals'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  { code:'B7', section:'B', name:'Research Centers & Institutes', max:4, score:3, value:2, unit:'centers',
    desc:'Functional research centers or institutes established at the university.',
    guide:'Score 4 if ≥3 centers · Score 2 if 2 · Score 1 if 1',
    reqDocs:['Center establishment notifications','Research profiles'],
    docs:[doc('Research_Centers_Profile.pdf','1.8 MB')],
    remarks:'2 centers: AI Research Center and Advanced Materials Lab.',
    status:'SUBMITTED', review:null },

  { code:'B8', section:'B', name:'Conference Papers & Presentations', max:4, score:3, value:38, unit:'papers',
    desc:'International and national conference papers presented by faculty.',
    guide:'Score 4 if ≥50 papers · Score 3 if 20–49 · Score 1 if <20',
    reqDocs:['Conference acceptance letters','Proceedings pages'],
    docs:[doc('Conference_Papers_List.xlsx','185 KB','xls')],
    remarks:'38 conference papers at IEEE, ACM and national conferences.',
    status:'SUBMITTED', review:null },

  { code:'B9', section:'B', name:'Books & Book Chapters', max:3, score:2, value:5, unit:'publications',
    desc:'Books authored or edited and book chapters published by faculty.',
    guide:'Score 3 if ≥10 · Score 2 if 5–9 · Score 1 if 1–4',
    reqDocs:['Publisher confirmation letters','ISBN records'],
    docs:[doc('Books_Chapters_Evidence.pdf','920 KB')],
    remarks:'5 book chapters in Springer and Elsevier volumes.',
    status:'APPROVED',
    review:{ rating:'perfect', comment:'Good publishing output. Publisher confirmations verified.', reviewer:'HEC Reviewer', date:'4 days ago' } },

  { code:'B10', section:'B', name:'HEC-Recognized Research Journals', max:2, score:2, value:2, unit:'journals',
    desc:'Research journals published by the university recognized by HEC.',
    guide:'Score 2 if ≥2 HEC-recognized journals · Score 1 if 1 · Score 0 if none',
    reqDocs:['HEC journal recognition letters','Sample issues'],
    docs:[doc('Journal_Recognition_HEC.pdf','640 KB')],
    remarks:'2 journals: DSU Journal of Computing and Engineering Journal.',
    status:'APPROVED',
    review:{ rating:'perfect', comment:'Both journals verified in HEC recognized list. Well documented.', reviewer:'HEC Reviewer', date:'5 days ago' } },

  { code:'B11', section:'B', name:'Research Management System (RMIS)', max:6, score:0, value:0, unit:'modules',
    desc:'Operational Research Management Information System with active modules.',
    guide:'Score 6 if RMIS fully operational (≥4 modules) · Score 3 if partial · Score 0 if none',
    reqDocs:['RMIS screenshots','IT dept confirmation'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  // ════════════════ SECTION C — Innovation & Commercialization (max 30) ════════════════
  { code:'C1', section:'C', name:'Patents Filed', max:5, score:5, value:4, unit:'patents',
    desc:'Patent applications filed with IPO-Pakistan or international offices.',
    guide:'Score 5 if ≥5 · Score 3 if 3–4 · Score 1 if 1–2',
    reqDocs:['Patent filing receipts','Application reference numbers'],
    docs:[doc('Patent_Filing_Receipts.pdf','1.1 MB')],
    remarks:'4 patents filed with IPO-Pakistan in the AI & materials domains.',
    status:'SUBMITTED', review:null },

  { code:'C2', section:'C', name:'Patents Granted', max:5, score:0, value:0, unit:'patents',
    desc:'Patents formally granted during the assessment year.',
    guide:'Score 5 if ≥3 · Score 3 if 2 · Score 1 if 1',
    reqDocs:['Grant certificates from IPO/USPTO'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  { code:'C3', section:'C', name:'Startups & Spin-offs', max:5, score:4, value:2, unit:'startups',
    desc:'University-affiliated startups incubated or spun off.',
    guide:'Score 5 if ≥3 · Score 3 if 2 · Score 1 if 1',
    reqDocs:['Incubation agreements','Company registration certificates'],
    docs:[doc('Incubation_Agreements.pdf','890 KB')],
    remarks:'2 startups incubated at the DSU Business Incubation Centre.',
    status:'SUBMITTED', review:null },

  { code:'C4', section:'C', name:'Technology Licensing Agreements', max:4, score:0, value:0, unit:'deals',
    desc:'Technology licensing agreements executed with industry partners.',
    guide:'Score 4 if ≥3 · Score 2 if 2 · Score 1 if 1',
    reqDocs:['Signed licensing agreements'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  { code:'C5', section:'C', name:'Industry-Sponsored Research Projects', max:4, score:3, value:3, unit:'projects',
    desc:'Research projects fully or partially funded by industry sponsors.',
    guide:'Score 4 if ≥4 projects · Score 2 if 2–3 · Score 1 if 1',
    reqDocs:['Sponsorship agreements','Project completion reports'],
    docs:[doc('Industry_Sponsored_Projects.pdf','1.3 MB')],
    remarks:'3 industry-sponsored projects with PTCL, Engro, and HBL.',
    status:'SUBMITTED', review:null },

  { code:'C6', section:'C', name:'Business Incubation Center', max:4, score:3, value:1, unit:'centers',
    desc:'Operational business incubation center supporting student/faculty entrepreneurship.',
    guide:'Score 4 if BIC with ≥5 active tenants · Score 2 if BIC with 1–4 · Score 0 if no BIC',
    reqDocs:['BIC registration','Active tenant list'],
    docs:[doc('DSU_BIC_Profile_2024.pdf','2.1 MB')],
    remarks:'DSU BIC operational with 3 active tenant startups.',
    status:'APPROVED',
    review:{ rating:'perfect', comment:'BIC fully operational with documented tenants. Approved.', reviewer:'HEC Reviewer', date:'6 days ago' } },

  { code:'C7', section:'C', name:'Innovation Awards & Recognitions', max:2, score:1, value:2, unit:'awards',
    desc:'National or international innovation awards received during the year.',
    guide:'Score 2 if ≥3 awards · Score 1 if 1–2 · Score 0 if none',
    reqDocs:['Award certificates','News coverage'],
    docs:[doc('Innovation_Awards_2024.pdf','780 KB')],
    remarks:'2 awards: NAVTTC innovation prize and a regional entrepreneurship award.',
    status:'SUBMITTED', review:null },

  { code:'C8', section:'C', name:'Technology Demonstrations & Exhibitions', max:1, score:0, value:0, unit:'events',
    desc:'Technology demonstration events or exhibitions showcasing university research.',
    guide:'Score 1 if ≥1 national/international tech exhibition participated in · Score 0 if none',
    reqDocs:['Exhibition participation letters','Booth photographs'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  // ════════════════ SECTION D — Sustainability & Capacity Building (max 15) ════════════════
  { code:'D1', section:'D', name:'Industry Collaborations (MoUs)', max:4, score:4, value:7, unit:'MoUs',
    desc:'Active signed MoUs with industry, public sector, or development partners.',
    guide:'Score 4 if ≥6 · Score 2 if 3–5 · Score 1 if 1–2',
    reqDocs:['Signed MoUs (active, within 3 years)'],
    docs:[doc('Industry_MoUs_2024.pdf','3.3 MB')],
    remarks:'7 active MoUs incl. NESPAK, K-Electric and 2 fintech firms.',
    status:'SUBMITTED', review:null },

  { code:'D2', section:'D', name:'Community Outreach Programs', max:3, score:3, value:9, unit:'programs',
    desc:'Public-good community outreach and knowledge-dissemination activities.',
    guide:'Score 3 if ≥8 programs · Score 2 if 4–7 · Score 1 if 1–3',
    reqDocs:['Event reports','Photographs','Attendance records'],
    docs:[doc('Outreach_Report_2024.pdf','4.7 MB')],
    remarks:'9 outreach programs including STEM school visits.',
    status:'APPROVED',
    review:{ rating:'perfect', comment:'Comprehensive outreach with strong evidence. Approved.', reviewer:'HEC Reviewer', date:'4 days ago' } },

  { code:'D3', section:'D', name:'Conferences & Seminars Hosted', max:3, score:0, value:0, unit:'events',
    desc:'Academic conferences, seminars and symposia organised by the university.',
    guide:'Score 3 if ≥5 events · Score 2 if 2–4 · Score 1 if 1',
    reqDocs:['Event brochures','Proceedings or programme schedules'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  { code:'D4', section:'D', name:'International Linkages', max:2, score:2, value:3, unit:'linkages',
    desc:'Active research collaborations with accredited foreign institutions.',
    guide:'Score 2 if ≥4 linkages · Score 1 if 1–3',
    reqDocs:['Collaboration or MoU agreements with foreign institutions'],
    docs:[doc('Intl_Collab_Agreements.pdf','1.6 MB')],
    remarks:'3 active linkages (UK, Malaysia, KSA).',
    status:'SUBMITTED', review:null },

  { code:'D5', section:'D', name:'Green & Sustainable Research Initiatives', max:2, score:0, value:0, unit:'initiatives',
    desc:'Research projects or programs focused on environmental sustainability and SDGs.',
    guide:'Score 2 if ≥3 active sustainability projects · Score 1 if 1–2 · Score 0 if none',
    reqDocs:['Project summaries','SDG alignment statements'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },

  { code:'D6', section:'D', name:'Media & Knowledge Dissemination', max:1, score:0, value:0, unit:'campaigns',
    desc:'Research findings disseminated through mainstream media, social media or public lectures.',
    guide:'Score 1 if ≥5 media features or public lectures during the year · Score 0 if none',
    reqDocs:['News clippings','Social media screenshots','Public lecture records'],
    docs:[],
    remarks:'',
    status:'DRAFT', review:null },
];

// recent activity feed for dashboard
const ACTIVITY = [
  { kind:'APPROVED', code:'B3', text:'Impact-Factor Publications approved',     time:'3 days ago' },
  { kind:'RETURNED', code:'A2', text:'Operating Budget returned for correction', time:'1 day ago'  },
  { kind:'APPROVED', code:'B10',text:'HEC-Recognized Journals approved',        time:'5 days ago' },
  { kind:'APPROVED', code:'C6', text:'Business Incubation Center approved',     time:'6 days ago' },
  { kind:'SUBMITTED',code:'B1', text:'HEC Research Proposals submitted',        time:'2 days ago' },
  { kind:'REJECTED', code:'B4', text:'PhD Graduates rejected — needs evidence', time:'1 day ago'  },
  { kind:'SUBMITTED',code:'C1', text:'Patents Filed submitted for review',      time:'3 days ago' },
  { kind:'DRAFT',    code:'A4', text:'Capacity-Building Trainings saved as draft','time':'5 days ago' },
];

window.DSUData = { SECTIONS, INDICATORS, ACTIVITY };
